name: "Release Goreleaser Project"
description: "Release a Goreleaser project using semantic-release"
branding:
  icon: upload-cloud
  color: blue

inputs:
  github-token:
    description: "GitHub token"
    required: false
    default: ${{ github.token }}
  setup-go:
    description: "Whether to setup go"
    required: false
    default: "false"
  go-version-file:
    description: "Path to go.mod file"
    required: false
    default: "go.mod"
  setup-goreleaser:
    description: "Whether to setup goreleaser"
    required: false
    default: "false"
  goreleaser-version:
    description: "Goreleaser version"
    required: false
    default: "latest"
  goreleaser-distribution:
    description: "Goreleaser distribution"
    required: false
    default: "goreleaser"

outputs:
  released:
    description: Whether a new release was published. The return value is in the form of a string. ("true" or "false")
    value: ${{ steps.semantic-release.outputs.new_release_published }}
  version:
    description: Version of the new release. (e.g. "1.3.0")
    value: ${{ steps.semantic-release.outputs.new_release_version }}
  major:
    description: Major version of the new release. (e.g. "1")
    value: ${{ steps.semantic-release.outputs.new_release_major_version }}
  minor:
    description: Minor version of the new release. (e.g. "3")
    value: ${{ steps.semantic-release.outputs.new_release_minor_version }}
  patch:
    description: Patch version of the new release. (e.g. "0")
    value: ${{ steps.semantic-release.outputs.new_release_patch_version }}
  channel:
    description: The distribution channel on which the last release was initially made available (undefined for the default distribution channel).
    value: ${{ steps.semantic-release.outputs.new_release_channel }}
  release-notes:
    description: The release notes for the new release.
    value: ${{ steps.semantic-release.outputs.new_release_notes }}
  git-head:
    description: The sha of the last commit being part of the new release
    value: ${{ steps.semantic-release.outputs.new_release_git_head }}
  git-tag:
    description: The Git tag associated with the new release.
    value: ${{ steps.semantic-release.outputs.new_release_git_tag }}
  prev-version:
    description: Version of the previous release, if there was one. (e.g. "1.2.0")
    value: ${{ steps.semantic-release.outputs.last_release_version }}
  prev-git-head:
    description: The sha of the last commit being part of the last release, if there was one.
    value: ${{ steps.semantic-release.outputs.last_release_git_head }}
  prev-git-tag:
    description: The Git tag associated with the last release, if there was one.
    value: ${{ steps.semantic-release.outputs.last_release_git_tag }}

runs:
  using: "composite"
  steps:
    - name: Setup Go
      if: ${{ inputs.setup-go }}
      uses: actions/setup-go@v4
      with:
        go-version-file: "${{ inputs.go-version-file }}"
    - name: Setup Goreleaser
      if: ${{ inputs.setup-goreleaser }}
      uses: goreleaser/goreleaser-action@v5
      with:
        install-only: "true"
        distribution: "${{ inputs.goreleaser-distribution }}"
        version: "${{ inputs.goreleaser-version }}"
    - name: Get semantic-release version
      shell: sh
      id: semantic-release-version
      run: "echo version=$(npm view @cihelper/semanticrelease-preset-goreleaser dependencies.semantic-release) >> $GITHUB_OUTPUT"
    - name: Run semantic-release
      id: semantic-release
      uses: cycjimmy/semantic-release-action@v4
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        semantic_version: ${{ steps.semantic-release-version.outputs.version }}
        extra_plugins: "@cihelper/semanticrelease-preset-goreleaser@1"
        extends: "@cihelper/semanticrelease-preset-goreleaser"
